name: synaptaid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  avatar_glow: ^2.0.2
  carousel_slider: ^4.2.1
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.0
  flutter_riverpod: ^2.5.1
  flutter_signature_pad: ^3.0.1
  flutter_tts: ^4.0.2
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  image: ^3.1.17
  image_gallery_saver: ^2.0.3
  language_tool: ^2.2.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.0
  speech_to_text: ^6.2.0
  tflite_flutter: ^0.10.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/images/
    - assets/icons/
    - assets/model_unquant.tflite
