// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDieocwqlo8-QizaxG4RRSY-kr7FEUJIKs',
    appId: '1:790637758280:web:1bde360f8631386f72557d',
    messagingSenderId: '790637758280',
    projectId: 'md-gemastik',
    authDomain: 'md-gemastik.firebaseapp.com',
    storageBucket: 'md-gemastik.appspot.com',
    measurementId: 'G-X3C727NSJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBANVJkqaWIziYBtP1G-6Nqn12NwjfmCdI',
    appId: '1:790637758280:android:cb0b8d601db91b2472557d',
    messagingSenderId: '790637758280',
    projectId: 'md-gemastik',
    storageBucket: 'md-gemastik.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuHEDlNV7ks_WtR8tssvn26y2-8N2Ep98',
    appId: '1:790637758280:ios:57dd1133a20df62d72557d',
    messagingSenderId: '790637758280',
    projectId: 'md-gemastik',
    storageBucket: 'md-gemastik.appspot.com',
    iosBundleId: 'com.gemastik.synaptaid.synaptaid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuHEDlNV7ks_WtR8tssvn26y2-8N2Ep98',
    appId: '1:790637758280:ios:57dd1133a20df62d72557d',
    messagingSenderId: '790637758280',
    projectId: 'md-gemastik',
    storageBucket: 'md-gemastik.appspot.com',
    iosBundleId: 'com.gemastik.synaptaid.synaptaid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDieocwqlo8-QizaxG4RRSY-kr7FEUJIKs',
    appId: '1:790637758280:web:4f112a42ee22205c72557d',
    messagingSenderId: '790637758280',
    projectId: 'md-gemastik',
    authDomain: 'md-gemastik.firebaseapp.com',
    storageBucket: 'md-gemastik.appspot.com',
    measurementId: 'G-QZMM5EEHZ9',
  );

}